### DISCUSSION TITLE
Is it possible to move the expand/contract indicator icon on details to the left

### DISCUSSION THREAD

**Discussion by Offbeatmammal** [shoelace-style/webawesome#1099] [Ideas & Suggestions]
I'm assuming, like everything else, there will be a way to dive into the CSS and make the change, but would be nice to have an attribute to choose if it's visually positioned on the left or the right (so similar to the RTL language layout, but maintaining the LTR orientation of the indicator)

**Comment by claviska** [comment]
Thanks for the suggestion. For now, you can indeed do it with CSS.

```css
wa-details::part(header) {
  flex-direction: row-reverse;
  justify-content: start;
  gap: .5em;
}
```

[CodePen example](https://codepen.io/claviska/pen/MYwRXyJ?editors=0100)
