### ISSUE TITLE
Making it easier to style components directly (without parts)

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#195]
### Discussed in https://github.com/shoelace-style/webawesome/discussions/192

<div type='discussions-op-text'>

<sup>Originally posted by **LeaVerou** November  1, 2024</sup>
Simply applying CSS properties to the component itself rarely works, because the actual rendered component is in a Shadow DOM `base` part, and the custom element itself is just a shell. This means that often to do simple things, one has to write rules with `::part(base)` all over the place, often even multi-level exported parts!

E.g. yesterday I wanted a radio group where the buttons were separate, like this:
<img width="451" alt="image" src="https://github.com/user-attachments/assets/90e46e59-67a0-4a02-90b8-a8702168fca6">

I had to do:

```css
wa-radio-group::part(button-group__base) {
  gap: .5em;  
}

wa-radio-button::part(button) {
  border-radius: var(--border-radius);
}
```

And that was not code I arrived to easily; it involved *a lot* of trial and error.
Ideally, it should be as simple as:

```css
wa-radio-group {
  gap: .5em;  
}

wa-radio-button {
  border-radius: var(--border-radius);
}
```

Why do we have `base`?
- If to account for the lack of `ElementInternals` or custom states at the time, that’s no longer an issue.
- If to account for the low cascade order of `:host` (and shadow styles in general), could we get away with `!important` for crucial declarations + Applied CSS in the light DOM for stying stuff?

Are there any other reasons? If not, could we perhaps get rid of it and style the custom element directly, at least in some cases?

If we can't get rid of it, would it make sense to apply `display: contents` to the custom element, and then inherit properties as needed in `base`?</div>
