### ISSUE TITLE
If a component fails to load, that content stays blank. For `<wa-page>` that means a completely blank page.

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#198]
Currently, Applied CSS has this rule:

```css
:where(:not(:defined, [did-ssr])), 
:where(:not(:defined, [did-ssr])) * {
  opacity: 0;
}
```

This works nicely to prevent FOUC, however it means that if there is a problem (e.g. something doesn't load), the end-user experience is to not get that content at all. In the case of `<wa-page>` that means a **completely blank page**, which goes contrary to the fault tolerance of HTML.

I’m a strong believer that in most cases we can have our cake and eat it too, so I was thinking: what about applying `opacity: 0;` via an animation, that will stop applying after a certain timeout?

```css
@keyframes wa-fade-in {
	from { opacity: 0 }
}

:where(:not(:defined, [did-ssr])), 
:where(:not(:defined, [did-ssr])) * {
  animation: 100ms 500ms fade-in both;
}
```

I haven’t tested this but I _think_ it should work: 
- if an element gets defined earlier than 500ms, the animation stops applying so it just appears (no fade)
- If an element takes longer than 600ms to get defined, it fades in over 100ms
- If it takes somewhere between 500 and 600 ms, then you may get an interrupted fade, but oh well

----

There is another issue with this that is trickier to solve. As currently written, this applies to _any_ non defined element, whether it belongs to WA or not. However, authors may want to use custom elements for all sorts of reasons, and there are valid use cases for using CE without _ever_ intending to define them. However, there is no way to only target CEs beginning with `wa-` unless we list them all (yikes).
