### ISSUE TITLE
Element shape utilities?

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#229]
We currently have a bunch of components that use an attribute to set element rounding:
- boolean `pill` attribute: `<wa-input>`,`<wa-button>`,`<wa-select>`,`<wa-badge>`,`<wa-radio-button>`,`<wa-tag>`
- `shape`=`square | rounded | circle`:  [`<wa-avatar>`](https://webawesome-git-next-font-awesome.vercel.app/docs/components/avatar#shapes)

This seems like a clear use case for a utility class, as it could be more broadly useful. But as usual, the devil is in the details. A first stab could be something like:

```css
.shape-pill,
.shape-circle {
  border-radius: calc(infinity * 1px);
}

.shape-circle {
  aspect-ratio: 1;
}

.shape-rounded {
  border-radius: var(--wa-border-radius);
}
```

However:
- `shape-rounded` is too long and noisy for something so frequently needed. I wonder if we may even want to make it an automatic part of whatever utilities add a backgrounds and outlines (see #223) — or would that be too opinionated and end up getting in the way?
- `shape-circle` won't work for elements without either a width or height

I would also love to explore what @lindsaym-fa suggested in #219 a bit more (bold mine):
> I can easily see existing attributes like `variant`, `appearance`, `pill`, `filled`, etc. becoming more generalized utility classes that could be used on any number of WA components, **and even parent containers to style multiple components or entire patterns at once**.
