### ISSUE TITLE
Make `visually-hidden` a utility class?

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#232]
I originally thought `<wa-visually-hidden>` may be adding some ARIA or something, but no, [it’s literally just styles](https://github.com/shoelace-style/webawesome/blob/next/src/components/visually-hidden/visually-hidden.ts)).

This seems like an excellent candidate for a utility class:
- It’s actually shorter that way
- It interferes with your DOM structure less (toggling a class is much easier than wrapping/unwrapping in virtually every workflow)
- It can be used everywhere

Based on https://github.com/shoelace-style/webawesome/blob/next/src/components/visually-hidden/visually-hidden.styles.ts it could look like:

```css
.wa-visually-hidden:not(:focus-within) {
    position: absolute !important;
    width: 1px !important;
    height: 1px !important;
    clip: rect(0 0 0 0) !important;
    clip-path: inset(50%) !important;
    border: none !important;
    overflow: hidden !important;
    white-space: nowrap !important;
    padding: 0 !important;
  }
```

We could even skip the `!important` since it will then have reasonable specificity.
