### ISSUE TITLE
Gap utils should also set `display: flex` with 0 specificity

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#265]
Currently, there is an error condition where if a novice author (or an experienced one that is a little distracted — as we all are) uses the gap utilities without also setting a display value that works with them or uses a layout utility class, they will do nothing.

What if they also set some sensible defaults around layout with 0 specificity so they could be overridden trivially? I.e. something like this:

```css
.gap-3xl,
.gap-2xl,
...
.gap-3xs {
  :where(&) {
    display: flex;
  }
}
```
