### ISSUE TITLE
Search dialog has fun padding now

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#331]
![Image](https://github.com/user-attachments/assets/00053dff-0f59-401a-8efc-7eef11e30ffb)

Looks like the new `inherit` styles are causing it.

**Comment by claviska** [comment]
@LeaVerou I believe this has something to do with the passthrough styles for dialog.

**Comment by lindsaym-fa** [comment]
I think @claviska's right. The search dialog is inheriting this from `<wa-page>` —
```css
::slotted(:not([slot])) {
  padding: var(--wa-space-3xl);
}
```

Not exactly sure how we want to handle this.
