### ISSUE TITLE
Dropdowns in button groups are misaligned and have different sizes than regular buttons

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#374]
<img width="334" alt="image" src="https://github.com/user-attachments/assets/254ea077-2a51-4eb2-89a4-9841c999066a" />

**Comment by claviska** [comment]
It looks like the button is also ~1px taller for some reason.

![Image](https://github.com/user-attachments/assets/339be627-662c-45f5-8d6b-2feb3904c0d7)

**Comment by claviska** [comment]
Adding `align-items: center` to `.wa-button-group` solved the alignment issue, but there's also a height issue that seems to be caused by something I cautioned about recently, which was _not_ setting an explicit height for form controls.

It looks like we're calculating these sizes now, which is causing some kind of rounding error.

```css
:root,
:host,
.wa-size-s,
.wa-size-m,
.wa-size-l {
  --wa-form-control-height: calc(2 * var(--wa-space-smaller) + 1em * var(--wa-form-control-value-line-height));
}
```

I'm not sure how we want to solve this, but here's what it looks like with the alignment fixed.

![Image](https://github.com/user-attachments/assets/a6866f98-5f3f-473e-88c6-b4aac74aef3e)

---

Aside: when removing the `base` part from button group, two aria attributes were added to the `<slot>` that were previously flagged as an accessibility violation. I'm not sure if it's disallowed by the spec or just a problem with assistive tech, but efforts were made in the past to remove such violations, e.g. https://github.com/shoelace-style/shoelace/issues/1287.

We need to start reviewing PRs to help catch things like this before we push through any more sweeping changes.
