### ISSUE TITLE
`--wa-form-control-height-[s|m|l]` isn't used consistently

### ISSUE THREAD

**Issue by lindsaym-fa** [shoelace-style/webawesome#413]
The size-based `--wa-form-control-height-*` custom properties we define in our themes isn't used consistently throughout components and isn't used at all in our size utilities, despite being documented on (local link) http://localhost:4000/docs/utilities/size/

`<wa-select>` appears to use `--wa-form-control-height-s` and `--wa-form-control-height-l` but not `--wa-form-control-height-m`:
<img width="407" alt="Image" src="https://github.com/user-attachments/assets/247221f2-1de1-4452-b296-d0424d10a688" />

Sliders appear to use `--wa-form-control-height-m`:
<img width="407" alt="Image" src="https://github.com/user-attachments/assets/b0b2c480-9f12-47c7-b3df-546b89613013" />

No other component, including `<wa-input>`, uses these custom properties. We should either use them or remove them — anything but using them inconsistently.

If we choose to remove them, they should also be scrubbed from documentation.

**Comment by LeaVerou** [comment]
The size utils define a `--wa-form-control-height` variable that automatically resolves to `--wa-form-control-height-[s|m|l]` depending on the size it’s used in, so the docs on size appear correct.

This is how it’s defined in `size.css`:

```css
:root,
:host,
.wa-size-s,
.wa-size-m,
.wa-size-l {
  --_wa-form-control-height: calc(2 * var(--wa-space-smaller) + 1em * var(--wa-form-control-value-line-height));
  --wa-form-control-height: var(--_wa-form-control-height);

  @supports (height: round(1.2px, 1px)) {
    --wa-form-control-height: round(var(--_wa-form-control-height), 1px);
  }
}
```

For `<wa-select>` it appears these were leftovers, since it already sets `min-height: var(--wa-form-control-height);` (which responds to size). Indeed, I just deleted it and it seems to cause no change.

Sliders are a curious case, they were using _only_ the medium size there before as well, so I left it that way: https://github.com/shoelace-style/webawesome/blob/16302c013063ca85088240e3054ac20466d8e9f4/src/components/range/range.css#L29
