### ISSUE TITLE
Make styling possible for `wa-checkbox` and `wa-radio` checked states

### ISSUE THREAD

**Issue by lindsaym-fa** [shoelace-style/webawesome#418]
Beyond our `--background-color-checked`, `--border-color-checked`, and `--checked-icon-color` custom properties on `wa-checkbox` and `wa-radio`, there doesn't seem to be a way to style checkboxes and radios that are checked. No selector I've tried is able to target them.

For my particular use case, I want to give the controls shadows to create depth, like this example from the Glassy theme on [a previous branch](https://webawesome-git-demo-patterns-font-awesome.vercel.app/experimental/kitchen-sink):
<img width="67" alt="Image" src="https://github.com/user-attachments/assets/90fdfeec-31d8-43ba-bce2-70e252b58f20" />

Now, however, I've found it impossible to create this same effect.

Previously, `wa-checkbox` was given a `checked` attribute when checked, making it easy to add styles like:
```css
wa-checkbox:is([checked], [indeterminate]) {
  --box-shadow: inset 0 0.0625rem 0 0 rgb(255 255 255 / 0.2) /* shine */,
    inset 0 0.125rem 0 0 rgb(255 255 255 / 0.05) /* top highlight */,
    inset 0 -0.0625rem 0 0 rgb(0 0 0 / 0.2) /* bottom highlight */, var(--wa-shadow-s) /* outer shadow */;
}
```

However, now, the `checked` attribute seems only to apply when manually set, not when the input is checked by the user. `wa-radio` never used it, but it did previously have a `control--checked` part that made styling possible. This part no longer exists.

Could we add a way to easily target checked instances of `wa-checkbox` and `wa-radio`, ideally in a way that's consistent? Is there a bug in `wa-checkbox` that prevents `checked` from being applied to the component when activated by a user?

**Comment by lindsaym-fa** [comment]
Never mind! targeting the following works perfectly:
```css
wa-checkbox:state(checked),
wa-radio:state(checked) {
  ...
}
```
