### ISSUE TITLE
`--box-shadow` and `--border-width` have no effect on `wa-input` and `wa-textarea`

### ISSUE THREAD

**Issue by lindsaym-fa** [shoelace-style/webawesome#419]
The `--box-shadow` and `--border-width` custom properties have no effect on `wa-input` or `wa-textarea`.

In `/src/styles/native/input.css`, we set `--box-shadow` and `--border-width` here:
```css
.wa-text-field,
:host,
textarea,
input:where(:not(
    /* Exclude inputs that don't accept text */
    [type='button'],
    [type='checkbox'],
    [type='color'],
    [type='file'],
    [type='hidden'],
    [type='image'],
    [type='radio'],
    [type='range'],
    [type='reset'],
    [type='submit']
  )) {
  /* Style native inputs and <wa-input>'s visible container */
  &:not(.wa-text-field *, :host input, :host textarea) {
    /* Do NOT reset --background-color and --border-color here so they trickle in from the appearance utils
     * Instead we provide the fallback when setting
     */
    --border-width: var(--wa-form-control-border-width);
    --box-shadow: initial;
    ...
}
```

...and call it here:
```css
/* Style text controls of inputs, including within <wa-input> */
  &:where(:not(:host, .wa-text-field :is(input, textarea))) {
    background-color: var(--background-color, var(--wa-form-control-background-color));
    border-width: var(--border-width);
    box-shadow: var(--box-shadow);
    padding: var(--wa-space-smaller) var(--wa-space);
    ...
}
```

However, setting either property on the component does nothing. Conversely, setting `--background-color` works just fine.
