### ISSUE TITLE
Expose system icons to CSS

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#466]
We currently embed a bunch of icons in a TS file: https://github.com/shoelace-style/webawesome/blob/next/src/components/icon/library.system.ts

I wonder if instead we could have a CSS file defining them like:

```css
:root, :host {
	--wa-icon-system-check: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512"><path d="M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z"/></svg>');
	/* ... */
}
```

Then, JS could just read those (and strip away the data URI), but that way we (and authors) can also use them in CSS like `var(--wa-icon-system-check)` without any (or very minimal) increase in filesize. This would also simplify some of our stylesheets where we duplicate these, e.g. https://github.com/shoelace-style/webawesome/blob/next/src/styles/native/checkbox.css#L35

Only wart is I'm not sure what should happen when people override the system library with their own resolver. I guess the resolver could take care of updating these variables?
