### ISSUE TITLE
Another idea to help with FOUCE

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#570]
We currently have this in our page styles to minimize FOUCE:

```css
@keyframes wa-fade-in {
  from {
    opacity: 0;
  }
}

/* Show custom elements only after they're registered */
:where(:not(:defined, [did-ssr])) {
  /*
	  * if an element gets defined earlier than 800ms, the animation stops applying so it just appears (no fade)
	  * If it takes somewhere between 800 and 1000 ms, then you may get an interrupted fade
	  * If an element takes longer than 1000ms to get defined, it fades in over 200ms
	  */
  animation: 200ms 800ms wa-fade-in both;
}
```

I wonder if we should separate it out into a separate utility and add the following selectors to it:

```css
:host(:has(:not(:defined):not([did-ssr]))), /* light DOM */
:host:has(:not(:defined):not([did-ssr])) /* shadow DOM */
```

I haven't tried it, so not sure it works, but in theory, this would also hide an element if it *contains* unregistered elements, either in its light DOM or shadow DOM. 
Also, making it a separate utility means it can be included even by folks not using Native Styles.

This does not preclude #486, I see them as orthogonal.
