### ISSUE TITLE
Native select is 100% but labels that wrap them aren't

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#578]
The native select is currently set to 100% width but, when wrapped with a `<label>` [as shown in the docs](https://backers.webawesome.com/docs/native/select), is incorrectly constrained by the label.

![Image](https://github.com/user-attachments/assets/53eec3c7-1f92-4692-b288-e74a0e7c83c7)

This seems like a relatively simply fix…

```css
/* src/styles/native/select.css */
label:has(select) {
  width: 100%;
  position: relative;
}
```

…except this causes clicks in the "whitespace" within the label to focus the select, which feels buggy.

![Image](https://github.com/user-attachments/assets/10708e56-3ffd-44dd-822c-6ee7cd7656e8)

~~Should we consider a grid-style layout where the label fits the content?~~ (This won't work without a container)

Adding a medium priority to this since it shows up in the docs like this.
