### ISSUE TITLE
Certain attributes (e.g. `variant`, `size`) should inherit when not explicitly set

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#580]
This is a spinoff out of #506 .

- Take a look at [this](https://backers.webawesome.com/docs/components/button-group#button-sizes). It should not take repeating `size` for every button! The author intent can be sufficiently signaled by an attribute on the group.
- Customer request here: https://github.com/shoelace-style/webawesome-alpha/discussions/139
- Same for `pill`: https://backers.webawesome.com/docs/components/button-group#pill-buttons
- Do you really still want a button to default to neutral within a brand callout?
- Etc. Pretty sure I've seen other cases around the library.

Inherited attributes have precedent in HTML too: that's how `lang` and `dir` behave.

Currently, our variant and size utils inherit, but only when used on native styles, e.g. see #454.

At first I tried to solve this in #512, but I think it should be separate, though it's better to tackle this after #506 is solved. Then we can just give them a default value of `inherit` and handle that.

It's not completely trivial to solve, mainly because these utils define default values on `:root`, but we want these to have _different_ default values on certain elements. E.g. the default variant overall is `neutral`, but callouts have a default variant of `brand`. How do we give these properties a default value that is different, without overriding the actual properties is still a known unknown.

**Comment by lindsaym-fa** [comment]
Fun! I was _just_ looking at [a backer idea related to small/large dropdowns](https://github.com/shoelace-style/webawesome-alpha/discussions/139), where they imagined something like this for `<wa-dropdown>`:
```html
<wa-dropdown size="small">
  <wa-button slot="trigger" caret>Dropdown</wa-button><!-- Inherits size attribute from dropdown -->
  <wa-menu>
    <wa-menu-item>Dropdown Item 1</wa-menu-item><!-- Inherits size attribute from dropdown -->
    <wa-menu-item>Dropdown Item 2</wa-menu-item>
    <wa-menu-item>Dropdown Item 3</wa-menu-item>
  </wa-menu>
</wa-dropdown>
```

**Comment by LeaVerou** [comment]
@lindsaym-fa Awesome, thanks! I added it to the first post, and I can now tag this "Request" 😁

**Comment by LeaVerou** [comment]
I’ve _really_ struggled with the CSS for this, so I'm going to write stuff down here for posterity. **Feel free to skip this unless you're interested in actively working on this problem.**

- Currently, `variants.css` sets variables like `--wa-color-fill-loud` to the corresponding specific tokens like `var(--wa-color-brand-fill-loud)` on selectors like `.wa-brand, :host([variant='brand'])`. This is currently 9 properties (`fill | border | on` &times; `loud | normal | quiet`) and 5 rules, corresponding to the 5 variants we have (but may later be more, as there have been discussions about including literal ones too).
- The properties inherit unless otherwise set, but are also set to the neutrals on `:root` so that they always resolve to something.
- Then, `appearance.css` uses these variables in variables like `--background-color` etc to implement the different appearances

However, we want certain elements like `callout` to have a different default (e.g. `callout` defaults to a `brand` variant, and I think that's a good default). But we don't want that default to override the inherited values, unless there is no inherited value. However, even with 0 specificity, applying a property directly _always_ wins over an inherited value.

So:
- A callout with no variant should inherit its variant from the closest ancestor elements with a variant (whether applied via a `variant` attribute, or a variant utility class)
- If no ancestor has a variant, then `brand` should be applied
- Any complexity should ideally be encapsulated in `variants.css`, using these variables should remain as simple as `var(--wa-color-fill-loud)` and they should continue to resolve to neutrals if not within an element with a non-neutral variant

## Idea 1: Separate initial & inherited properties 

In the following I'll use `--wa-color-fill-loud` as a placeholder for all of them, since whatever we do applies exactly in the same way to all 9 properties.

Instead of `--wa-color-fill-loud` properties, each variant sets `--wa-color-fill-loud-inherit` properties:

```css
.wa-neutral,
:host([variant='neutral']) {
	--wa-color-fill-loud-inherit: var(--wa-color-neutral-fill-loud);
}

.wa-brand,
:host([variant='brand']) {
	--wa-color-fill-loud-inherit: var(--wa-color-brand-fill-loud);
}
```

Then elements set their defaults as `--wa-color-fill-loud-initial` properties:

```css
:root {
	--wa-color-fill-loud-initial: var(--wa-color-neutral-fill-loud);
}

:host(wa-callout),
.wa-callout {
	--wa-color-fill-loud-initial: var(--wa-color-brand-fill-loud);
}
```

Then, at the end, there is a selector that applies to everything relevant that combines the two.
The selector is as general as that because false positives are ok, but false negatives are bad. We could have even applied it to everything, but I try to avoid that.

```css
:root,
:host,
[class*="wa-"]
--wa-color-fill-loud: var(--wa-color-fill-loud-inherit, var(--wa-color-fill-loud-initial));
```

This is very verbose, but the way it works is obvious: these two properties cascade separately, and are combined wherever relevant.

## Idea 2: `--wa-no-variant` space toggle

Thinking some more about this problem, as I _really_ didn't like the idea of having 3 different properties. Basically, inheritance is lower priority in CSS *unless* explicitly specified via `inherit`. Could we somehow leverage explicit `inherit` to increase the priority of inherited values within variants?

Some more observations:
- Basically, once you have *any* ancestor with an explicit variant, you want to _only_ change variant when explicitly set (via the attribute or utility class) and ignore any element defaults.
- If *no* ancestor has an explicit variant, then you want element defaults to just cascade normally.
- When do you NOT inherit? 
  - When the element is an explicit variant
  - When the element has a default variant and is NOT inside an explicit variant
- So when DO you inherit?
  - When the element is NOT an explicit variant, NOT inside an explicit variant, and does NOT have any defaults.

Two things that make this tricky:
1. You cannot pass a literal `inherit` around as a custom property value — it just makes the custom property itself inherit.
2. There is no selector that will match "elements inside a variant" across shadow roots. `:host-context()` is not supported by Firefox or Safari, and worse yet, is not planned either. The only thing that reliably transcends shadow roots is CSS variables, so we need to use a variable… somehow.

But it doesn't need to be a different variable for everything we're setting! All we need to know is whether we're inside a variant or not, that can be done with a single `--wa-no-variant` variable. But then, how do we use it?

We can use style queries to define the element defaults, but they are [still not supported in Firefox](https://caniuse.com/css-container-queries-style).

What if we use the space toggle hack to _only_ set element defaults when `--wa-no-variant` is `initial`?

It would look like this:

```css
/* Element defaults */
.wa-callout, :host(wa-callout) {
	--wa-color-fill-loud: var(--wa-no-variant, var(--wa-color-brand-fill-brand));
}

/* Variants + root, basically the existing code */
:where(:root),
.wa-neutral, :host([variant="neutral"]) {
	--wa-color-fill-loud: var(--wa-color-neutral-fill-loud);
}

.wa-brand, :host([variant="brand"]) {
	--wa-color-fill-loud: var(--wa-color-brand-fill-loud);
}

/* … 3 more … */

/* All variants */
.wa-brand, 
.wa-neutral, 
.wa-danger,
.wa-success,
.wa-warning,
:host([variant]) {
  --wa-no-variant: /* space toggle */;
}
```

This _feels_ a lot simpler to me, though there is the ugliness of the space toggle hack. But it's internal, contained ugliness, and termporary, until FF implements style queries. Aside from that, variants are defined exactly the same way they already are. 

Though I wonder, could the extra properties in Idea 1 be useful on their own, with proper naming?

----

Edit: So the issue with this solution is that when a variant-less element is within a variant-ful element, it gets *no* color properties. Example:

<img width="750" alt="Image" src="https://github.com/user-attachments/assets/5720f7c6-fc34-4afd-bc84-575c5a60aaff" />

The problem was that the space toggle hack doesn't work for unregistered properties, because space is a perfectly valid value for them! To solve it, we need to register them all as `<color>`. I wonder if there's a better solution, but for now that seems to work well.
