### ISSUE TITLE
Certain token mappings are not applying

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#645]
https://github.com/shoelace-style/webawesome-alpha/discussions/163

User: "Why doesn't my code work to use a larger shadow with a bigger spread?"

Their code:
```css
wa-avatar {
    box-shadow: var(--wa-shadow-l);
    --wa-shadow-spread-l: 2.0rem;
}
```

The relevant design tokens (other decls omitted) in `themes/default/shadows.css`:

```css
:where(:root),
:host {
  --wa-shadow-spread-scale: -0.5;
  --wa-shadow-spread-l: calc(var(--wa-shadow-spread-scale) * 0.5rem);

  --wa-shadow-l: var(--wa-shadow-offset-x-l) var(--wa-shadow-offset-y-l) var(--wa-shadow-blur-l)
    var(--wa-shadow-spread-l) var(--wa-color-shadow);
}
```

So the issue is, this is not one of the stylesheets included in a component's shadow DOM, so the mappings are only applied on `:root`, so overridding `--wa-shadow-spread-l` on `wa-avatar` does nothing.

Solutions:

This user's particular problem can be solved by just adding `:state(wa-defined)` to the list of selectors. However, this will not help with other elements they may want to add shadows to, e.g. native elements. Or even parts.

For this particular issue, we could also add a set of shadow utilities, which also redefine the mapping. This doesn't solve the root issue, but it does mitigate it.

Ultimately, the only real solution is to define mappings on `*`, like so:

```css
:where(:root),
:host {
  --wa-shadow-spread-scale: -0.5;
  --wa-shadow-spread-l: calc(var(--wa-shadow-spread-scale) * 0.5rem);
}

* {
  --wa-shadow-l: var(--wa-shadow-offset-x-l) var(--wa-shadow-offset-y-l) var(--wa-shadow-blur-l)
    var(--wa-shadow-spread-l) var(--wa-color-shadow);
}
```

But it feels …wrong to define these on every single element on the page, even if they are `--wa` prefixed.
It also means they would no longer inherit when explicitly set: if someone sets `--wa-shadow-l` on an element, its descendants would still get `--wa-shadow-l: var(--wa-shadow-offset-x-l) var(--wa-shadow-offset-y-l) var(--wa-shadow-blur-l) var(--wa-shadow-spread-l) var(--wa-color-shadow);` because targeting an element directly has higher precedence than any inherited value.

Yeah, I’m at a loss.
