### ISSUE TITLE
Idea to simplify our CSS and make custom states easier down the line

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#824]
**tl;dr:** Introduce `--wa-color`/`--wa-color-N` for an element’s "core" accent color, drop semantic role tokens

## How variants are currently implemented

Currently, we implement our roles/states (brand/neutral/success/warning/danger) this way:

**1. Literal role mappings**, implemented via mixin files in `src/styles/[role]/[color].css`

<details><summary>

#### Example: [`src/styles/brand/blue.css`](https://github.com/shoelace-style/webawesome/blob/next/src/styles/brand/blue.css)

</summary>

```css
:where(:root),
:host,
:where([class^='wa-theme-'], [class*=' wa-theme-']),
:where([class^='wa-palette-'], [class*=' wa-palette-']),
.wa-brand-blue {
  --wa-color-brand-95: var(--wa-color-blue-95);
  --wa-color-brand-90: var(--wa-color-blue-90);
  --wa-color-brand-80: var(--wa-color-blue-80);
  --wa-color-brand-70: var(--wa-color-blue-70);
  --wa-color-brand-60: var(--wa-color-blue-60);
  --wa-color-brand-50: var(--wa-color-blue-50);
  --wa-color-brand-40: var(--wa-color-blue-40);
  --wa-color-brand-30: var(--wa-color-blue-30);
  --wa-color-brand-20: var(--wa-color-blue-20);
  --wa-color-brand-10: var(--wa-color-blue-10);
  --wa-color-brand-05: var(--wa-color-blue-05);
  --wa-color-brand: var(--wa-color-blue);

  --wa-color-brand-lt-50: var(--wa-color-blue-lt-50);
  --wa-color-brand-gte-50: var(--wa-color-blue-gte-50);

  --wa-color-brand-lt-60: var(--wa-color-blue-lt-60);
  --wa-color-brand-gte-60: var(--wa-color-blue-gte-60);

  --wa-color-brand-lt-70: var(--wa-color-blue-lt-70);
  --wa-color-brand-gte-70: var(--wa-color-blue-gte-70);

  --wa-color-brand-max-50: var(--wa-color-blue-max-50);
  --wa-color-brand-min-50: var(--wa-color-blue-min-50);
  --wa-color-brand-max-60: var(--wa-color-blue-max-60);
  --wa-color-brand-min-60: var(--wa-color-blue-min-60);
  --wa-color-brand-max-70: var(--wa-color-blue-max-70);
  --wa-color-brand-min-70: var(--wa-color-blue-min-70);

  --wa-color-brand-on: var(--wa-color-blue-on);
}
```

</details> 

**2. Semantic role mappings** Themes map these literal role tints to semantic role tokens (`--wa-color-[role]-[tint]` → `--wa-color-[role]-[semantic-suffix]`). This involves a lot of repetition as the mapping of `tint` → `semantic-suffix` is the same across roles (2x for dark mode):

<details><summary>

#### Example: Role color mappings from the Default theme (light mode only)
</summary>

```css
--wa-color-brand-fill-quiet: var(--wa-color-brand-95);
--wa-color-brand-fill-normal: var(--wa-color-brand-90);
--wa-color-brand-fill-loud: var(--wa-color-brand-max-50);
--wa-color-brand-border-quiet: var(--wa-color-brand-90);
--wa-color-brand-border-normal: var(--wa-color-brand-80);
--wa-color-brand-border-loud: var(--wa-color-brand-60);
--wa-color-brand-on-quiet: var(--wa-color-brand-40);
--wa-color-brand-on-normal: var(--wa-color-brand-30);
--wa-color-brand-on-loud: white;

--wa-color-success-fill-quiet: var(--wa-color-success-95);
--wa-color-success-fill-normal: var(--wa-color-success-90);
--wa-color-success-fill-loud: var(--wa-color-success-max-50);
--wa-color-success-border-quiet: var(--wa-color-success-90);
--wa-color-success-border-normal: var(--wa-color-success-80);
--wa-color-success-border-loud: var(--wa-color-success-60);
--wa-color-success-on-quiet: var(--wa-color-success-40);
--wa-color-success-on-normal: var(--wa-color-success-30);
--wa-color-success-on-loud: white;

--wa-color-warning-fill-quiet: var(--wa-color-warning-95);
--wa-color-warning-fill-normal: var(--wa-color-warning-90);
--wa-color-warning-fill-loud: var(--wa-color-warning-max-50);
--wa-color-warning-border-quiet: var(--wa-color-warning-90);
--wa-color-warning-border-normal: var(--wa-color-warning-80);
--wa-color-warning-border-loud: var(--wa-color-warning-60);
--wa-color-warning-on-quiet: var(--wa-color-warning-40);
--wa-color-warning-on-normal: var(--wa-color-warning-30);
--wa-color-warning-on-loud: white;

--wa-color-danger-fill-quiet: var(--wa-color-danger-95);
--wa-color-danger-fill-normal: var(--wa-color-danger-90);
--wa-color-danger-fill-loud: var(--wa-color-danger-max-50);
--wa-color-danger-border-quiet: var(--wa-color-danger-90);
--wa-color-danger-border-normal: var(--wa-color-danger-80);
--wa-color-danger-border-loud: var(--wa-color-danger-60);
--wa-color-danger-on-quiet: var(--wa-color-danger-40);
--wa-color-danger-on-normal: var(--wa-color-danger-30);
--wa-color-danger-on-loud: white;

--wa-color-neutral-fill-quiet: var(--wa-color-neutral-95);
--wa-color-neutral-fill-normal: var(--wa-color-neutral-90);
--wa-color-neutral-fill-loud: var(--wa-color-neutral-20);
--wa-color-neutral-border-quiet: var(--wa-color-neutral-90);
--wa-color-neutral-border-normal: var(--wa-color-neutral-80);
--wa-color-neutral-border-loud: var(--wa-color-neutral-60);
--wa-color-neutral-on-quiet: var(--wa-color-neutral-40);
--wa-color-neutral-on-normal: var(--wa-color-neutral-30);
--wa-color-neutral-on-loud: white;
```

</details> 

**3. Generic semantic tokens** These are then mapped to generic `--wa-color-[semantic-suffix]` tokens in `variants.css` that components and native styles can use without having to worry about variants (defaulting to neutral on the root, so that they’re always available)

<details><summary>

#### Example for `success` variant from `variants.css`
</summary>

```css
.wa-success,
:host([variant='success']) {
  --wa-color-fill-loud: var(--wa-color-success-fill-loud);
  --wa-color-fill-normal: var(--wa-color-success-fill-normal);
  --wa-color-fill-quiet: var(--wa-color-success-fill-quiet);
  --wa-color-border-loud: var(--wa-color-success-border-loud);
  --wa-color-border-normal: var(--wa-color-success-border-normal);
  --wa-color-border-quiet: var(--wa-color-success-border-quiet);
  --wa-color-on-loud: var(--wa-color-success-on-loud);
  --wa-color-on-normal: var(--wa-color-success-on-normal);
  --wa-color-on-quiet: var(--wa-color-success-on-quiet);
}
```

</details> 

## Issues

There are several issues with this approach:
- With states being so hardcoded, it becomes very hard to add additional states or literal color states (which Dave, Lindsay, and I were in agreement are needed down the line).
- There is a lot of knowledge duplication. The mapping of `tint` → `semantic-suffix` is the same across roles, yet it still needs to be repeated for every role.
- No way to access tints outside these three and stay within the same variant.

## Proposal

The fact that the `tint` → `semantic-suffix` mapping is the same across roles makes me think we’re mapping in the wrong order.
Instead of:

literal color token → literal role token → semantic role token → semantic generic token

Perhaps it should be:

literal color token → literal role token → <del>semantic role token</del> <ins>literal generic token</ins> → semantic generic token

Meaning, `variants.css` would set generic literal `--wa-color-N` tokens instead of generic semantic tokens.

<details><summary>Example</summary>
<p>

Instead of this in `variants.css`:

```css
.wa-success,
:host([variant='success']) {
  --wa-color-fill-loud: var(--wa-color-success-fill-loud);
  --wa-color-fill-normal: var(--wa-color-success-fill-normal);
  --wa-color-fill-quiet: var(--wa-color-success-fill-quiet);
  --wa-color-border-loud: var(--wa-color-success-border-loud);
  --wa-color-border-normal: var(--wa-color-success-border-normal);
  --wa-color-border-quiet: var(--wa-color-success-border-quiet);
  --wa-color-on-loud: var(--wa-color-success-on-loud);
  --wa-color-on-normal: var(--wa-color-success-on-normal);
  --wa-color-on-quiet: var(--wa-color-success-on-quiet);
}
```

We'd do this:

```css
.wa-success,
:host([variant='success']) {
  --wa-color: var(--wa-color-success);
  --wa-color-key: var(--wa-color-success-key);
  --wa-color-95: var(--wa-color-success-95);
  --wa-color-90: var(--wa-color-success-90);
  --wa-color-80: var(--wa-color-success-80);
  --wa-color-70: var(--wa-color-success-70);
  --wa-color-60: var(--wa-color-success-60);
  --wa-color-50: var(--wa-color-success-50);
  --wa-color-40: var(--wa-color-success-40);
  --wa-color-30: var(--wa-color-success-30);
  --wa-color-20: var(--wa-color-success-20);
  --wa-color-10: var(--wa-color-success-10);
  --wa-color-05: var(--wa-color-success-05);
}
```

</p>
</details> 

Then, theme CSS assigns `--wa-color-N` to generic semantic tokens (only twice — once for light mode and once for dark mode).

<details><summary>Example</summary>
<p>

```css
--wa-color-fill-quiet: var(--wa-color-95);
--wa-color-fill-normal: var(--wa-color-90);
--wa-color-fill-loud: var(--wa-color-max-50);
--wa-color-border-quiet: var(--wa-color-90);
--wa-color-border-normal: var(--wa-color-80);
--wa-color-border-loud: var(--wa-color-60);
--wa-color-on-quiet: var(--wa-color-40);
--wa-color-on-normal: var(--wa-color-30);
--wa-color-on-loud: white;
```

</p>
</details> 

Then, defining custom states becomes a matter of 11 declarations and a selector, which can easily be generated by the themer too:

```css
.wa-info,
:host([variant='info']) {
  --wa-color: var(--wa-color-blue);
  --wa-color-key: var(--wa-color-blue-key);
  --wa-color-95: var(--wa-color-blue-95);
  --wa-color-90: var(--wa-color-blue-90);
  --wa-color-80: var(--wa-color-blue-80);
  --wa-color-70: var(--wa-color-blue-70);
  --wa-color-60: var(--wa-color-blue-60);
  --wa-color-50: var(--wa-color-blue-50);
  --wa-color-40: var(--wa-color-blue-40);
  --wa-color-30: var(--wa-color-blue-30);
  --wa-color-20: var(--wa-color-blue-20);
  --wa-color-10: var(--wa-color-blue-10);
  --wa-color-05: var(--wa-color-blue-05);
}
```

## Impact

So what would be the impact of this change?
We would gain generic `--wa-color-*` literal tokens that let us use color tints that automatically respond to the specified variant, but we would lose the semantic role tokens `--wa-color-[role]-[suffix]` and would only have generic semantic tokens `--wa-color-[suffix]`.
This is not all-or-nothing, we could end up with one or two scales of semantic role tokens (e.g. neutral and brand) if the impact of removing them would be too much, and still get the benefits.

So how widely are semantic role tokens used, outside of variant assignments?
Searching for `var\(--wa-color-(brand|neutral|success|warning|danger)-(on|fill|border)-` (regexp) in `src/styles/**/*.css` and excluding `variants.css` yields **56** results.
What are these used for?

Breakdown by role:
- `neutral`: 33
- `brand`: 8
- `success`: 7
- `danger`: 7
- `warning`: 1

- 10 are in `forms.css`, setting styles for `.wa-invalid` and `.wa-valid`.
- 5 are in `appearance.css` as neutral fallbacks in case the generic ones are not defined (which shouldn't be needed)
- 16 are in element styles:
  - (1) `mark` sets `background-color: var(--wa-color-warning-fill-quiet);`. 
  - (1) `blockquote` sets `background-color: var(--wa-color-neutral-fill-quiet);`
  - (2) Button uses it as a fallback for generic tokens (e.g. `var(--wa-color-fill-loud, var(--wa-color-neutral-fill-loud))`) which shouldn't be necessary
  - (1) Checkbox sets `--checked-icon-color: var(--wa-color-brand-on-loud);`
  - (2) `kbd` to set its color to neutral
  - (2) `ins` to set its color to success
  - (2) `del` to set its color to danger
  - (3) Progress sets `--indicator-color` and `color` to brand colors and `background-color` to a neutral
  - (2) Slider sets `--track-color-active` and `--track-color-inactive` to `var(--wa-color-neutral-fill-normal)`
- 8 themes set `--wa-form-control-border-color`, 7 to `var(--wa-color-neutral-border-normal);` and 1 to `var(--wa-color-neutral-border-loud)`
- 4 themes set `--wa-form-control-activated-color`, 3 to neutrals, and 1 to `var(--wa-color-brand-fill-loud);`
- 13 are in theme overrides (5 themes):
  - 2 themes set `--checked-icon-color: var(--wa-color-brand-on-loud);` for radios
  - (3) Tailspin sets avatar's and switch's colors to neutral

The vast majority of these seem far better represented as setting the default variant of certain selectors to a given role rather than effectively reimplementing it their styles. We likely still need a `neutral` scale, as that seems much more widely used [^1]. We may end up needing a `brand` scale as well, though it may be possible to avoid it.

[^1]: and down the line we may want to support styles that mix accent and neutral, as they are common in design systems, e.g. a neutral button with colored icons and/or hover effects
