### ISSUE TITLE
`variant` → `color` + `intent` (names TBB) + `--wa-color` CSS property

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#876]
As discussed with @claviska over the Snuggle. Related to #268, which tracks the higher-level problem and #824 which tracks one of the implementation facets.

## Proposal

This separates the presentational core color of an element (`color`) from its semantic purpose (`intent`), allowing the latter to do more than simply set color defaults down the line (see FAQ below for use cases).

Names TBB, but I'll use `color` and `intent` for the sake of discussion:
* `intent` is the higher level semantic attribute. It accepts values such as `success`, `warning`, `danger` but can easily accommodate more, and possibly even user-defined ones down the line, e.g. `info`.
* `color` accepts:
  * literal color scale names like `red` , `green` etc (which in the future may be user-defined), 
  * semantic colors such as `brand` and `neutral`
  * any valid `intent` (which sets the core color, but does not affect anything else)
* `color` is also settable as a CSS property (`--wa-color`) but `intent` is not. `intent` sets `--wa-color` so they don't have to be specified twice.
* Just like other styling attributes, the end goal is that `color` becomes an attribute only used in niche use cases to override defaults. In most cases, it is only set by components and themes.

### Why would we do that? (Use cases)

Across many design systems, intents (especially `danger`) affect styling in way more ways than simply setting an element's color. For example, check out the [GitHub Primer buttons](https://primer.style/product/components/button/#style-variants):

![Image](https://github.com/user-attachments/assets/d33fe538-806d-4e4e-bd5e-bfbfbe22fa94)

These also vary a button's `appearance`, and this styling is specific to `danger` intents, not across the entire design system.

Changing the appearance or even color variant on hover is especially common for dangerous actions, as it’s a compromise between two conflicting design goals: reducing the visual impact of the dangerous action, but also using red to communicate that it’s dangerous.

Here’s another example (Slack context menu):

![Image](https://github.com/user-attachments/assets/72104048-b76b-4fdc-8a25-206af6989fc6)

This would also allow us to have richer styling for other components, e.g. it's common for callouts to have default icons that vary by intent, which would now be possible via:

```css
wa-callout[intent=success] {
  --wa-icon-name: circle-check;
}

wa-callout[intent=warning] {
  --wa-icon-name: triangle-exclamation;
}

wa-callout[intent=warning] {
  --wa-icon-name: circle-exclamation;
}
```

Down the line, this allows us to have user-defined intents too, e.g.:

```css
wa-callout[intent=info] {
  --wa-color: blue;
  --wa-icon-name: circle-info;
}
```

Additionally:
- It makes [color utility classes](https://github.com/shoelace-style/webawesome/issues/223) (#223) a lot easier.
- It also provides a solution to #441.

### Does every component need to support every intent?

Currently, every component that supports `variant` supports every `variant`. But when do we actually need a `warning` button, ever? Looking at [the table here](https://github.com/shoelace-style/webawesome/issues/878) it appears that the only intent that buttons need is basically `danger` (the rest are basically priorities wherever used).

On the other hand, `callout` seems to need ALL the intents, including custom ones like `info` or `note` and `badge` is served well by our current set. 

### What should we call them? 

I think `color` for the presentational attribute seems rather uncontroversial, so the question is mainly what to call the semantic attribute.

We need to consider the range of components that this will work on (not just buttons) and the widest set of potential future values (e.g. `info`, `tip`, `note`, etc). 

No strong opinion, some ideas are:
- `intent`
- `role`
- `state`
- `variant`

### Why would `color` also accept semantic intents? Wouldn't that be confusing?

There are use cases where we want to refer to a color by its semantic purpose, without pulling in the entire danger styling, e.g. for invalid states in form controls:

```css
:invalid, :state(invalid), :host(:state(invalid)) {
  --wa-color: danger;
}
```

Or referring to them in custom intents:

```css
wa-callout[intent=success] {
  --wa-color: success;
}
```

Yes, there is the risk of users using `color="danger"` instead of `intent="danger"` and being puzzled why they did not get the full danger styling, but on balance, I think the flexibility is worth it (not a strong opinion though).

### Setting accent color to `neutral` for disabled controls:

```css
[disabled] {
  --wa-color: neutral;
}
```

### GitHub Primer danger buttons

Note that this would also need https://github.com/shoelace-style/webawesome/issues/877

![](https://private-user-images.githubusercontent.com/175836/392177008-441aac6f-ea09-4c7f-bdb2-2070079f2484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUyNDQ2MTMsIm5iZiI6MTc0NTI0NDMxMywicGF0aCI6Ii8xNzU4MzYvMzkyMTc3MDA4LTQ0MWFhYzZmLWVhMDktNGM3Zi1iZGIyLTIwNzAwNzlmMjQ4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQyMVQxNDA1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Yjg0YzRlZmFmMDdhMzFjYTY1YzA2MGM5NjE4NWFmNTk2YmY0Nzc1ODQ2MjM0MGVhYzAxMmE4Yzg4MWY1MWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xM9RNkBJ-djozrbg7xQL9j8PbAtYSlz6c96prCl7vdU)

```css
wa-button[intent=danger] {
  --wa-appearance: outlined;

  &:is(:hover, :active) {
     --wa-appearance: accent;
  }
}
```
