### ISSUE TITLE
Allow `appearance` to be set via `--wa-appearance`

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#877]
Related to #268, which tracks the higher-level problem. It is also part of #430, and the next natural step after setting icon params. 

## Problems this solves

This would solve several problems we currently have.

### 1. Allow themes to set different `appearance` defaults

Currently, a component's default `appearance` is specified in the component and themes cannot override it. For example, because the default `appearance` for buttons is `accent`, the Awesome theme needs to basically make every button outlined:

![Image](https://github.com/user-attachments/assets/6d793a42-ca22-40e8-b91d-6e0cde3bbf7b)

With this, the Awesome theme can just do:

```css
wa-button {
	--wa-appearance: outlined accent;
}
```

That way, the theme can define _actual_ `accent` and `filled` styles without being forced to use them as defaults.

### 2. Allow appearance to vary based on user interaction

For example take a look at the GitHub Primer buttons:

![Image](https://github.com/user-attachments/assets/0615be7f-b5ef-4cd5-88c1-5fc76b9c5246)

The `danger` variant actually involves **changing the `appearance` on hover/active**:

```css
wa-button[intent=danger] {
  --wa-appearance: outlined;

  &:is(:hover, :active) {
     --wa-appearance: accent;
  }
}
```

### 3. Allow themes to override our interaction defaults

Currently, our appearances encode certain design decisions about what happens when a control is interacted with. For example, our outlined buttons essentially emulate `appearance="filled outlined"` when hovering an `appearance=outlined` button, and `appearance=filled` when hovering an `appearance=plain` button:

![Image](https://github.com/user-attachments/assets/5ed78b82-7fd1-4ea7-a1c6-521e1aa6318a)

However, different design systems make different choices. For example, another common treatment, is to emulate `appearance=accent` when hovering `appearance=outlined`, notably used by [IBM Carbon](https://carbondesignsystem.com/components/button/style/):

![Image](https://github.com/user-attachments/assets/32394e15-38d6-4e57-8d29-7831870f2ae6)

Or even to emulate `appearance=accent` when hovering `appearance=plain`, like this Slack context menu:

![Image](https://github.com/user-attachments/assets/656e7280-d2b2-4c30-8898-77b02abf0677)

**Set appearance based on a state or attribute, e.g. `checked`.**

<img width="421" alt="Image" src="https://github.com/user-attachments/assets/32ee719c-8b25-43bf-b7d7-9daef51a7d5a" /> 

This pattern can be specified by basically switching from `appearance=plain` to `appearance=accent` when the option is checked.

### 4. Allow appearance to vary by context

Example 1: Buttons may default to `appearance=accent` in general, but when used inside a `<wa-radio-group>` we want them to default to `appearance=outlined` when unchecked and `appearance=”outlined filled”` when checked. This is currently done with entirely duplicate components, but can become as simple as:

```css
wa-radio-group > wa-button {
  --wa-appearance: outlined;
}

wa-radio-group > wa-button[checked] {
  --wa-appearance: outlined filled;
}
```

Example 2: the default appearance for an input is `outlined`, but it's common to switch to `filled` when inside a card. This can be done via:

```css
wa-card wa-input {
  --wa-appearance: filled;
}
```

## Implementation notes

#447 laid out most of the groundwork for this. However, it is not enough to simply define `cssProperty: '--wa-appearance'` wherever an `appearance` prop is defined as **we don't want `appearance` to inherit**.

So we also need to **register it** in `appearance.css`:

```css
@property --wa-appearance {
	syntax: "outlined | filled | accent | plain | outlined filled | outlined accent | none";
	inherits: false;
	initial-value: none;
}
```

Or, to avoid specifying an initial value:

```css
@property --wa-appearance {
	syntax: "**";
	inherits: false;
}
```

I think this might make implementation a little easier (due to how the code checks whether the property is set), but it may not be needed.
