### ISSUE TITLE
`priority` attribute (name TBB)

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#878]
Related to #268, which tracks the higher-level problem.
Depends on:
- https://github.com/shoelace-style/webawesome/issues/876
- https://github.com/shoelace-style/webawesome/issues/877

> [!NOTE]
> I don't have a strong opinion about naming (discussion bellow) but for the sake of communication, I'll use `priority = urgent | high | medium | low` in the rest of this.

Instead of encoding what priorities look like manually on every component instance, we introduce a `priority` attribute which can be used as a styling hook by themes to set defaults. This depends on styling attributes affected by priority being settable via CSS, otherwise it provides no benefit, and only makes the syntax more cumbersome. The idea is that instead of writing

```html
<wa-button appearance="outlined" variant="neutral">OK</wa-button>
``` 

Folks can just write 

```html
<wa-button priority="high">OK</wa-button>
``` 

and what that means is defined by the theme and can change when picking another theme.

Because `priority` is higher level than styling attributes, it can make more assumptions, e.g. set ARIA attributes accordingly (e.g. aria-live for priority="urgent", as well as set defaults for the styling attributes so that they rarely need to be explicitly specified, shifting design responsibility from component usage to themes.

This would affect these components:
- button
- badge
- radio-button (if we keep it)

Additionally, it _might_ make sense on:
- callout
- toast (once we have it)

### Theme-sensitive styling defaults

The main value of this is to allow themes to encode their design decisions about to communicate priority, rather than encoding on the component instance, which would make them a lot more powerful.

Let's use buttons as an example. Our current default styling would look like this:

```css
wa-button {
  --wa-appearance: outlined; /* or filled ? */

  &[priority=high] {
    --wa-appearance: accent;
  }

  &[priority=low] {
    --wa-appearance: plain;
  }
}
```

A [GitHub Primer](https://primer.style/product/components/button/#style-variants) inspired theme could do:

![Image](https://github.com/user-attachments/assets/bd99872e-1819-4a14-8ba1-c02a70b1f675)

```css
wa-button {
  &:not([priority=high], [priority=low]) {
    --wa-appearance: filled outlined;
  }

  &[priority=high] {
    --wa-appearance: accent outlined;
    --wa-color: success;
  }
}
```

While an [Adobe Spectrum](https://spectrum.adobe.com/page/button/) inspired theme could do:

<img width="271" alt="Image" src="https://github.com/user-attachments/assets/8ab4abed-1485-417a-9aeb-44088f985ee1" />

Looking at https://spectrum.adobe.com/page/button/#Options it's actually unclear what the ordering is, as they seem to have both an outlined and accented version of a button for every priority level (!) but a stab at it could look like this:

```css
wa-button {
  --wa-color: brand;
  --wa-appearance: outlined;

  &[priority=high] {
    --wa-appearance: accent;
  }

  &[priority=low] {
    --wa-color: neutral;
  }
}
```

### Badge effect to draw attention

Currently, [badges have a pulse attribute](https://backers.webawesome.com/docs/components/badge#pulsating-badges), whose purpose is “to draw attention to the badge with a subtle animation”. This fits perfectly in here:

```css
wa-badge {
  &[priority=urgent] {
    animation: var(--wa-animation-pulse);
  }
}
```

Now, the exact effect becomes a styling choice that can vary by theme.

And as a bonus, we could even have defaults for the other three prorities, e.g.:

```css
wa-badge {
  &[priority=low] {
    --wa-color: neutral;
    --wa-appearance: outlined;
  }
}
```

### Accessibility & improved UI

Because `priority` tells us more about the author intent than styling attributes, it can also make more assumptions, e.g. set ARIA attributes accordingly (e.g. `aria-live` for priority="urgent").

## Naming

Some ideas below:

- `priority = urgent | high | medium | low`
- `priority = urgent | higher | normal | lower`
- `attention = immediate | loud | normal | quiet`

A few more, that I'm not a huge fan of:
- `?? = primary | secondary | tertiary` (very common but has several issues, see below)
- `hint = encourage | normal | discourage` (too weird and uncommon, hard to extend, conflicts with our current `hint` attribute)

What do other design systems do? Here are a few examples:

| Design System | Attribute name | Values |
|----------------|----------------|--------|
| [Adobe Spectrum](https://opensource.adobe.com/spectrum-web-components/components/button/#variants) | `variant` | `accent`, `primary`, `secondary`, `negative`, `white`, and `black` |
| [GitHub Primer](https://primer.style/product/components/button/#style-variants) | `variant` | `primary`, `default`, `invisible`, `danger` |
| [IBM Carbon](https://web-components.carbondesignsystem.com/?path=/story/components-button--default) | `kind` | `primary`, `secondary`, `tertiary`, `danger`, `danger-tertiary`, `danger-ghost`, `ghost` |
| [Ant design](https://ant.design/components/button) | `type` | `primary`, `default`, `dashed`, `text`, `link` |
| [Atlassian](https://atlassian.design/components/button/examples#appearance) | `appearance` | `primary`, `subtle`, `warning`, `danger`, `discovery` |
| [Nord](https://nordhealth.design/components/button/) | `variant` | `default`, `primary`, `danger`, `dashed`, `plain` |

Observations:
-  It’s all over the place. Visual appearance is often mixed with priority and role, which causes awkwardness like `danger-tertiary` and `danger-ghost` values down the line.
- Most (all?) of these design systems can get away with poor design around these because unlike WA, **they don't need to describe a wide variety of designs**, just their own with minor theming modifications.
- Many need additional custom states that they describe either semantically (`discovery`) or presentationally (`dashed`).
- `primary`, `secondary` etc are very common terms, but have several problems for our use case:
  - They do not generalize well to multiple components
  - They lack an obvious default value, which is why that tends to be just `default` in these taxonomies, but it's unclear where that fits among primary, secondary, tertiary.
