### ISSUE TITLE
Add hover media query to all hover styles

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#990]
It's kind of annoying, but we should add the following media query around all `:hover` declarations in all components and theme overrides to prevent touch devices from leaving trails.

Reported here in Shoelace: https://github.com/shoelace-style/shoelace/issues/2444

Thankfully, we can nest it like so:

```css
a {
  background: lightblue;
  color: black;

  @media (hover: hover) {
    &:hover {
      background: darkblue;
      color: white;
    }
  }
}
```
